### ISSUE TITLE
Public Access of Lower Matrix L

### ISSUE THREAD

**Issue by ajos6183** [wo80/CSparse.NET#13]
Hi @wo80 ,

Would it be possible to provide public access for the Lower Matrix L in the SparseCholesky Factorization?
I am trying to implement the below method, so that would be of great help.
![image](https://user-images.githubusercontent.com/32379403/46733235-6dfcfa80-ccdb-11e8-9ee8-ec20eb6465a7.png)

Regards,
Anthony

**Comment by wo80** [comment]
I've once implemented this as an extension for Math.NET Numerics dense matrix: [DenseMatrixExtensions.cs](https://github.com/wo80/mathnet-extensions/blob/master/src/Numerics/LinearAlgebra/Double/DenseMatrixExtensions.cs#L23)

I'm not sure that for sparse matrices this is the right way to go. The matrix `L^{-1} * K_G * L^{-T}` will most likely not be sparse anymore.

Additionally, you'll have to take the fill reducing permutation into account. For now, you can get the data using reflection (not tested!):
```c#
CompressedColumnStorage<double> GetFactorL(SparseCholesky cholesky)
{
    var info = typeof(SparseCholesky).GetField("L", BindingFlags.Instance | BindingFlags.NonPublic);

    return info.GetValue(cholesky) as CompressedColumnStorage<double>;
}

int[] GetPinv(SparseCholesky cholesky)
{
    var info = typeof(SparseCholesky).GetField("S", BindingFlags.Instance | BindingFlags.NonPublic);

    var S = info.GetValue(cholesky) as SymbolicFactorization;

    return S.pinv;
}
```

I will think about making the members public, but this only makes sense, if I do the same for the other factorizations. Please leave this issue open.

**Comment by ajos6183** [comment]
Thank you that was what i needed!
I didn't think about the matrix `L^{-1} * K_G * L^{-T}` being dense. That's true.

I also looked at your implementation and that was very helpful. But sadly, it seems that this method is not very computationally efficient to find the minimum positive eigenvalue of this system even when combining it with the power method (instead of the MATH.NET EVD).

**Comment by romainmesnil** [comment]
Hello @wo80 
I would like to use the QR decomposition to perform null-space computation of sparse matrices (I'm using MathNET at the moment). To do so, having access to the members Q and R is necessary, so there could be some utility in having public members for this factorization too.
Best,
Romain

**Comment by epsi1on** [comment]
Hi @romainmesnil,

    CompressedColumnStorage<double> GetFactorR(SparseQR qr)
    {
        var info = typeof(SparseQR).GetField("R", BindingFlags.Instance | BindingFlags.NonPublic);
        return info.GetValue(qr) as CompressedColumnStorage<double>;
    }


    CompressedColumnStorage<double> GetFactorQ(SparseQR qr)
    {
        var info = typeof(SparseQR).GetField("Q", BindingFlags.Instance | BindingFlags.NonPublic);
        return info.GetValue(qr) as CompressedColumnStorage<double>;
    }

**Comment by romainmesnil** [comment]
Hello,
it came really useful thank you. However, it took me some time to understand that in `CSparse`, `Q` does not contain the Q matrix, but rather the Householder vectors, it is possible to retrieve the matrix Q by multiplying all the Householder matrix but it's quite expensive. To reconstruct the Householder matrix H, we need the factors beta so that H=I-beta*V*Transpose(V). So we also need that.

```csharp
double[] GetFactorBeta(SparseQR qr)
{
    var info = typeof(SparseQR).GetField("beta", BindingFlags.Instance | BindingFlags.NonPublic);
    return info.GetValue(qr) as double[];
}
```
 I don't know how this compares to a more classical method in terms of performance... Probably not ideal, but it allows to keep everything tied with the same package.
Thanks for the help,
Romain

**Comment by wo80** [comment]
I'm closing this issue, since I don't think that many users will feel the need to access the internal factorization data. I've added a wiki page for those who need: [factorization members](https://github.com/wo80/CSparse.NET/wiki/Factorization-members)

Additionally - since I wanted to know how to accomplish this - there's a gist showing how to calculate the actual Q factor of the sparse QR factorization: [CreateQFromSparseQR.cs](https://gist.github.com/wo80/5a3fea8cb48196a1a11797a328aea33b)
