### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by AlbertLiDesign** [wo80/CSparse.NET#37]
Hi,

It's me again. Sorry for interrupting.

I'm working on a Finite element system based on Unity. I used CSparse.NET and Math.NET. I found that the bottleneck is matrix processing and computing, such as Multiply(), Get_Item() and CompressedColumnStorage.OfIndexed(). It means that matrix editing and computing is much slower than solving the linear system.

The Multiply() and Get_Item() I used is Math.NET. But how can I implement them in CSparse? I want to make it as fast as my Matlab program.

![微信截图_20211126213018](https://user-images.githubusercontent.com/39052060/143684738-cff578a5-495f-4839-9cfc-f5921ce99c8e.png)

Best wishes

**Comment by wo80** [comment]
First two general remarks:
1) Accessing a sparse matrix by index A(i,j) is always expensive, since it's not O(1) like for dense matrices, but involves a binary search O(log n).
2) Try to avoid memory allocations. Especially in Math.NET those are sometimes not obvious (might be the case for Transpose and Multiply methods).

CSparse.NET matrix `OfIndexed` and `SubMatrix` are expected to be expensive, but there might be room for improvement. Is your code publicly available?

I will be away from my computer now, so don't expect a response until tomorrow. Have a nice weekend!

**Comment by AlbertLiDesign** [comment]
Many thanks for your reply. 

This is the FE part and the GetDC part. 

I don't know why MATLAB is so fast. Just because it uses MKL?

Have a nice weekend!


`nelx` and `nely` are integers.

``` C#
private void FE()
    {
        int num_allDofs = 2 * (nelx + 1) * (nely + 1);
        int num_fixedDofs = 2 * (nely + 1);
        int num_freeDofs = num_allDofs - num_fixedDofs;

        // Assemble stiffness matrix with all DOFs
        var sK = new double[64 * nelx * nely];
        for (int i = 0; i < nelx; i++)
        {
            for (int j = 0; j < nely; j++)
            {
                for (int a = 0; a < 8; a++)
                {
                    for (int b = 0; b < 8; b++)
                    {
                        sK[i * nely * 64 + j * 64 + a * 8 + b] = Math.Pow(Xe[j, i], p) * Ke[a, b];
                    }
                }
            }
        }
        var coo = new CoordinateStorage<double>(num_allDofs, num_allDofs, sK.Length, ik, jk, sK);
        var K = (CSparseMatrix)CSparseMatrix.OfIndexed(coo);

        var F = new double[num_allDofs];
        U = new double[num_allDofs];

        // Define force vector
        F[2 * (nelx + 1) * (nely + 1) - nely - 1] = -1.0;

        // Define fixed dofs
        var fixed_dofs = new int[num_fixedDofs];
        for (int i = 0; i < num_fixedDofs; i++)
            fixed_dofs[i] = i;

        var all_dofs = new int[num_allDofs];
        for (int i = 0; i < num_allDofs; i++)
            all_dofs[i] = i;

        // Obtain free dofs
        var free_dofs = all_dofs.Except(fixed_dofs).ToArray();

        // Assemble global stiffness matrix with free dofs
        var K_freedof = (CSparseMatrix)K.SubMatrix(free_dofs, free_dofs);

        var F_freedof = new double[num_freeDofs];
        var U_freedof = new double[num_freeDofs];

        for (int i = 0; i < num_freeDofs; i++)
        {
            F_freedof[i] = F[free_dofs[i]];
        }
        if (OutputK) OutputMatrix.WriteMatrix(K_freedof, @"E:\test\new.mat");

        // Solve KU = F

        //var cholmod = new Cholmod(K_freedof);
        //cholmod.Solve(F_freedof, U_freedof);

        var pardiso = new Pardiso(K_freedof);
        pardiso.Solve(F_freedof, U_freedof);
        for (int i = 0; i < num_freeDofs; i++)
        {
            U[free_dofs[i]] = U_freedof[i];
        }
    }
```

Get DC
``` C#
    private void GetDc()
    {
        Compliance = 0.0;
        for (int ely = 0; ely < nely; ely++)
        {
            for (int elx = 0; elx < nelx; elx++)
            {
                var n1 = (nely + 1) * elx + ely + 1;
                var n2 = (nely + 1) * (elx + 1) + ely + 1;

                double[,] ary = { { U[2 * n1 - 2] }, { U[2 * n1 - 1] }, { U[2 * n2 - 2] }, { U[2 * n2 - 1] },
                    { U[2 * n2] }, { U[2 * n2 + 1] }, { U[2 * n1] }, {U[2 * n1 + 1] } };
                var Ue = DenseMatrix.OfArray(ary);
                double v = Ue.TransposeThisAndMultiply(Ke).Multiply(Ue)[0, 0];

                Compliance += 0.5 * Math.Pow(Xe[ely, elx], p) * v;
                dc[elx * nely + ely] = 0.5 * Math.Pow(Xe[ely, elx], p - 1) * v;
            }
        }
    }
```

**Comment by epsi1on** [comment]
i did looked at the code, is `SubMatrix()` for sparse matrix is out-of-box? didn't find it in this library. maybe that is bottleneck.
I think handling sparse matrix is a little complicated and needs caution as its structure is different than dense matrix. As far as I know there is no need to access total stiffness matrix elements by i,j index. i mean you should use other methods that do not need this.
Thanks

**Comment by AlbertLiDesign** [comment]
@epsi1on 

Thank you for your reply. `SubMatrix()` is a method to the csparse-extensions project, which is discussed [here](https://github.com/wo80/CSparse.NET/issues/36). I plan to rewrite this part by myself to avoid access elements by i,j index.

Thank you for your help, and sorry for my interruption.

Cheers

**Comment by wo80** [comment]
No need to apologize, you're very welcome to ask questions!

So lets talk about your code.

In your `GetDc()` method, all memory should be allocated outside of the nested loops:
1) Allocate the 8x1 vector `ary` outside of the loops and set the elements one by one. Make it a 1-dimensional array, it probably doesn't need to be matrix.
2) `DenseMatrix.OfArray(ary)` makes a copy of the data (memory allocation). Use `var Ue = new DenseMatrix(8, 1, ary)` instead (or `new DenseVector(ary)`, if it doesn't need to be a matrix).
3) Look out for methods like `Vector<T> Multiply(Vector<T> other)`. In Math.NET, you usually have a twin method `void Multiply(Vector<T> other, Vector<T> result)`. If the result is allocated beforehand, you can avoid the memory allocation.

Now the main `FE()` method:

As I said, `OfIndexed` is expected to be expensive and `SubMatrix` uses that method. Since your sub matrix is approximately of the same size as the full system matrix, this will be slow. In general, to make your FE code as efficient as possible, assemble only the free nodes.

EDIT:

In CSparse.NET, you can set a flag `SparseMatrix.AutoTrimStorage = false` to avoid memory allocations that are done when trimming the storage arrays to actually match their non-zeros count. Additionally, `OfIndexed` can take a parameter `bool inplace`, which also avoids new memory allocations by reusing the coordinate storage arrays for the CSC storage. But those won't make a big difference here...

**Comment by wo80** [comment]
Maybe modifying the stiffness matrix to eliminate the equations is another option for you, see https://github.com/wo80/csparse-extensions/commit/052d8cbf6ac1342c8977bdcd39fa3609797b0ddd

This means the solver has to deal with a larger system, but it still could be faster than extracting the sub matrix.

**Comment by wo80** [comment]
I've also added a symmetric version of `SubMatrix` which should be faster, see https://github.com/wo80/csparse-extensions/commit/8e4b105d5e1c8199c69174172f997ad1771a2929

**Comment by epsi1on** [comment]
> I've also added a symmetric version of `SubMatrix` which should be faster, see [wo80/csparse-extensions@8e4b105](https://github.com/wo80/csparse-extensions/commit/8e4b105d5e1c8199c69174172f997ad1771a2929)

This is more programmer-friendly in my opinion :)

Maybe i asked this question before, but solving the linear FEM system can be seen in a bigger picture.

Generally we have two equation system

**EQ system 1:** Describing the system equations, (this is before eliminate fixed DoFs, call `SubMatrix()`)

`[K] * [X] = [F]`

 *Sizes*: `[K]` is `n*n`, `[X]` and `[F]` are `n*1`
 *Note*: `[K]` is singular. 

**EQ system 2:** Describing the constraints:

`[A] * [X] = [B]`

*Sizes*: `[A]` is `m*n`, `[X]` and `[F]` are `n*1`.
*Note 1*: `m` is number of constrains, 
*Note 2*: `nonzero` members is each row of `[A]` can be more than one (in case of handling complex constraints)

Now imagine there is need to eliminate variables in the first system with regard to second system. Is there any straight forward method to do so?
Thanks

**Comment by AlbertLiDesign** [comment]
Thank you all. I have modified my code according to your suggestions. The performance have an obvious improvement. Thank you sooooooo much!

**Comment by AlbertLiDesign** [comment]
Thank you all. I have modified my code according to your suggestions. The performance have an obvious improvement. Thank you sooooooo much!

**Comment by wo80** [comment]
@AlbertLiDesign I think the estimation of the sub matrix non-zeros count doesn't make too much sense at the moment. I've added a corrected version, which uses a hash set and might be slower (https://github.com/wo80/csparse-extensions/commit/e17658f545c3b7ec321a08eeefaeaf56c5c292e1)

I've also added an overload, that takes the target sub matrix as input. So, the fasted way to go: if you know the sub matrix will have approximately the same non-zeros count as the full matrix (as in your case), just initialize a matrix with the correct row/column count and the **non-zeros count of the original matrix** and pass this as the target matrix.

**Comment by wo80** [comment]
> Is there any straight forward method to do so?

@epsi1on not sure what you consider _straight forward_. You want to find the dependent variables of system 2 to eliminate those from system 1. QR can solve the underdetermined system 2, but I'm not sure if it's helpful to extract the set of dependent/independent variables. We discussed this in https://github.com/wo80/CSparse.NET/issues/7
